/**
 * SEED Observatory — Interact View
 * Preserves the existing ability to interact with SEED's actual model.
 * Supports selecting a compatible model if multiple trained models become available.
 */
export async function renderInteract(container, data) {
  if (!container) return;

  const models = data.models || [];

  container.innerHTML = `
    <div class="panel">
      <nav class="breadcrumb" aria-label="Breadcrumb">
        <span class="crumb">OBSERVATORY <span class="slash">/</span> INTERACT</span>
      </nav>

      <header class="section-header">
        <span class="kicker">LIVE INTERACTION</span>
        <h2>Interact with SEED</h2>
      </header>

      <p class="lede">Interact with SEED's actual trained model. This is not a wrapper — responses come from our own trained neural model running locally in your browser.</p>

      <div class="interact-controls" style="margin-bottom: var(--space-4); display: flex; gap: var(--space-3); flex-wrap: wrap; align-items: center;">
        <label style="font-family: var(--mono); font-size: 11px; color: var(--ink-muted);">Model:</label>
        <select id="interact-model-select" class="btn outline" style="min-width: 280px;">
          <option value="seed-0">SEED-0 (default)</option>
        </select>
        <span style="color: var(--ink-muted); font-family: var(--mono); font-size: 11px;">Temperature:</span>
        <input type="range" id="interact-temp" min="0.1" max="1.5" step="0.05" value="0.75" style="width: 120px;">
        <span id="temp-value" style="font-family: var(--mono); font-size: 11px; color: var(--ink-muted); min-width: 30px;">0.75</span>
      </div>

      <div class="chat-container" style="background: var(--recessed); border: 1px solid var(--border); border-radius: var(--radius); overflow: hidden; height: 400px; display: flex; flex-direction: column;">
        <div class="chat-messages" id="chat-messages" style="flex: 1; overflow-y: auto; padding: var(--space-4); display: flex; flex-direction: column; gap: var(--space-3);">
          <div class="chat-message seed" style="align-self: flex-start; background: var(--canvas); color: var(--ink); border: 1px solid var(--border); border-radius: var(--radius) var(--radius) var(--radius) 0; padding: var(--space-2) var(--space-3); max-width: 85%;">
            <div class="msg-label" style="font-family: var(--mono); font-size: 10px; letter-spacing: 1px; color: var(--ink-muted); margin-bottom: 4px; text-transform: uppercase;">SEED / neural</div>
            <div>Hello! I'm SEED, a tiny neural experiment trained from scratch. I don't know much yet — that's the point. Try asking me something or teach me something new!</div>
          </div>
        </div>

        <div class="chat-input" style="display: flex; gap: var(--space-2); padding: var(--space-3); border-top: 1px solid var(--border); background: var(--canvas);">
          <textarea id="interact-prompt" rows="2" placeholder="Ask SEED something..." maxlength="2000" style="flex: 1; min-height: 48px; max-height: 120px; padding: var(--space-2) var(--space-3); border: 1px solid var(--border); border-radius: var(--radius); resize: vertical; font-family: inherit;"></textarea>
          <button id="interact-send" class="btn primary" style="align-self: flex-end;" aria-label="Send message">↗</button>
        </div>
      </div>

      <div class="interact-status" id="interact-status" role="status" aria-live="polite" style="margin-top: var(--space-3); font-family: var(--mono); font-size: 12px; color: var(--ink-muted);">
        LOCAL / NO API — Responses generated by SEED's own neural model running in your browser.
      </div>

      <details class="model-info" style="margin-top: var(--space-6);">
        <summary style="cursor: pointer; font-family: var(--mono); font-size: 11px; color: var(--ink-muted);">Model Architecture Details</summary>
        <div class="model-specs" style="margin-top: var(--space-3); display: flex; flex-direction: column; gap: var(--space-2); font-size: 13px;">
          <div class="model-spec"><span class="model-spec-label">Architecture</span><span class="model-spec-value">SEED-0 (seed0-context3-mlp)</span></div>
          <div class="model-spec"><span class="model-spec-label">Parameters</span><span class="model-spec-value">6,672</span></div>
          <div class="model-spec"><span class="model-spec-label">Context Length</span><span class="model-spec-value">3 characters</span></div>
          <div class="model-spec"><span class="model-spec-label">Embedding Dim</span><span class="model-spec-value">8</span></div>
          <div class="model-spec"><span class="model-spec-label">Hidden Units</span><span class="model-spec-value">48</span></div>
          <div class="model-spec"><span class="model-spec-label">Activation</span><span class="model-spec-value">tanh</span></div>
          <div class="model-spec"><span class="model-spec-label">Output</span><span class="model-spec-value">softmax over 96-char vocabulary</span></div>
        </div>
      </details>
    </div>
  `;

  initInteractView();
}

function initInteractView() {
  // For now, SEED-0 is the only available model
  // In the future, this would load different trained models

  const promptEl = document.getElementById('interact-prompt');
  const sendBtn = document.getElementById('interact-send');
  const messagesEl = document.getElementById('chat-messages');
  const tempInput = document.getElementById('interact-temp');
  const tempValue = document.getElementById('temp-value');
  const statusEl = document.getElementById('interact-status');

  // Temperature display update
  if (tempInput && tempValue) {
    tempInput.addEventListener('input', () => {
      tempValue.textContent = parseFloat(tempInput.value).toFixed(2);
    });
  }

  // Load SEED-0 model for interaction
  let seedModel = null;
  let brain = null;

  async function loadSeedModel() {
    try {
      // Import the SEED-0 model from observatory model file
      const { SeedModel, Brain } = await import('../model.js');
      seedModel = new SeedModel({ seed: 1337 });
      
      // Create a brain instance with in-memory storage (not localStorage)
      const memoryStore = new Map();
      const mockStorage = {
        getItem: (key) => memoryStore.get(key) || null,
        setItem: (key, value) => memoryStore.set(key, value),
      };
      brain = new Brain(mockStorage);
      
      // Override the model with our instance
      brain.model = seedModel;
      
      return true;
    } catch (error) {
      console.error('Failed to load SEED model:', error);
      return false;
    }
  }

  // Initialize on load
  loadSeedModel().then(loaded => {
    if (loaded) {
      document.getElementById('interact-status').textContent = 'MODEL LOADED — LOCAL / NO API';
    } else {
      document.getElementById('interact-status').textContent = 'FAILED TO LOAD MODEL';
    }
  });

  // Send message handler
  async function sendMessage() {
    const prompt = document.getElementById('interact-prompt')?.value?.trim();
    if (!prompt) return;

    const messagesEl = document.getElementById('chat-messages');
    if (!messagesEl) return;

    // Add user message
    appendMessage(messagesEl, 'you', prompt);
    document.getElementById('interact-prompt').value = '';

    // Show thinking indicator
    const thinkingEl = document.createElement('div');
    thinkingEl.className = 'chat-message seed thinking';
    thinkingEl.innerHTML = `
      <div class="msg-label">SEED / thinking</div>
      <div><span class="spinner"></span> Generating...</div>
    `;
    messagesEl.appendChild(thinkingEl);
    messagesEl.scrollTop = messagesEl.scrollHeight;

    // Generate response
    try {
      // Use the brain's respond method which includes memory lookup
      // For now, use direct model generation
      const temperature = document.getElementById('interact-temp')?.value || 0.75;
      const response = seedModel?.generate({ prompt, maxChars: 180, temperature: parseFloat(temperature) });
      
      // Remove thinking indicator
      thinkingEl.remove();

      // Add model response
      appendMessage(messagesEl, 'seed', response || 'I don\'t know how to respond yet.', 'neural');
    } catch (error) {
      thinkingEl.remove();
      appendMessage(messagesEl, 'seed', `Error: ${error.message}`, 'error');
    }
  }

  function appendMessage(container, who, text, method = '') {
    const article = document.createElement('article');
    article.className = `message ${who}`;

    const label = document.createElement('div');
    label.className = 'message-label';
    label.textContent = who === 'you' ? 'YOU' : `SEED / ${method.toUpperCase()}`;

    const body = document.createElement('div');
    body.className = 'message-body';
    body.textContent = text;

    article.append(label, body);
    container.append(article);
    container.scrollTop = container.scrollHeight;
  }

  // Event handlers
  document.getElementById('interact-send')?.addEventListener('click', sendMessage);
  document.getElementById('interact-prompt')?.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  });

  // Temperature display
}